# Generated by Django 2.2.7 on 2019-11-28 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dict', '0004_auto_20191126_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.Word')),
            ],
        ),
    ]
