# Generated by Django 2.2.7 on 2020-04-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0007_auto_20200427_0216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
    ]
