# Generated by Django 2.2.7 on 2020-04-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0008_auto_20200427_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
